name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: linz/action-typescript@v1

      - name: Set up Docker Qemu
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set GIT_VERSION
        id: version
        run: |
          GIT_VERSION=$(git describe --tags --always --match 'v*')
          echo "::set-output name=version::${GIT_VERSION}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: "basemaps-screenshot/cli - Build and push"
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: linux/arm64,linux/amd64
          tags: ghcr.io/linz/basemaps-screenshot/cli:${{ steps.version.outputs.version }}
          push: false
